### ISSUE TITLE
Нужен дополнительный шаг в настройке

### ISSUE THREAD

**Issue by kirill-fedyanin** [CommanderDuck/express_ml#1]
Для корректного работы интерактивных штук нужно было включить экстеншн (на линуксе, по крайней мере)
Добавить в инструкцию по установке?
jupyter nbextension enable --py --sys-prefix widgetsnbextension

**Comment by SlinkoIgor** [comment]
ну тут такое... оно же само об этом говорит варнингом. И установку не хочется делать слишком длинной. Если не лень, кинь pull-request - замерджу
